services:
  vite-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0  # Use 0.0.0.0 for container access
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    command: python main.py
    environment:
      - FLASK_APP=main.py
    networks:
      - app-network

  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    hostname: my-database-hostname
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/xyz_enterprises.sql:/docker-entrypoint-initdb.d/xyz_enterprises.sql
    environment:
      - MYSQL_DATABASE=xyz_enterprises
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
networks:
  app-network:
    driver: bridge

volumes:
  db-data:

secrets:
  db-password:
    file: ./db/password.txt
